import type { ClassInfo } from "./types"
import { mockUsers } from "@/entities/user/model/mock-users"

const studentUser = mockUsers.find((u) => u.id === "u2")!

export const mockClasses: ClassInfo[] = [
  {
    id: 1,
    name: "Математика 10А",
    subject: "Математика",
    description:
      "Курс по математике для учеников 10А класса. Включает алгебру, геометрию, тригонометрию и начала математического анализа.",
    schedule: "Понедельник, среда, пятница — 9:00–10:30",
    classroom: "Кабинет 305",
    entryCode: "MATH10A",
    teacher: "Иванова Елена Петровна",
    activeAssignments: 3,
    image: "/class/math.jpg",
    students: [
      {
        id: studentUser.id,
        firstName: studentUser.firstName,
        lastName: studentUser.lastName,
        email: studentUser.email,
        gender: studentUser.gender,
        avatar: studentUser.avatar,
        averageGrade: 78,
        lastActive: "2025-05-10T09:30:00",
      },
      {
        id: "s101",
        firstName: "Иван",
        lastName: "Иванов",
        email: "ivanov.ivan@school.edu",
        avatar: "/avatars/male1.png",
        gender: "male",
        averageGrade: 85,
        lastActive: "2025-05-10T14:30:00",
      },
      {
        id: "s102",
        firstName: "Алексей",
        lastName: "Петров",
        email: "petrov.aleksey@school.edu",
        avatar: "/avatars/male2.png",
        gender: "male",
        averageGrade: 72,
        lastActive: "2025-05-09T16:45:00",
      },
      {
        id: "s103",
        firstName: "Мария",
        lastName: "Сидорова",
        email: "sidorova.maria@school.edu",
        avatar: "/avatars/female2.png",
        gender: "female",
        averageGrade: 95,
        lastActive: "2025-05-10T10:15:00",
      },
      {
        id: "s104",
        firstName: "Дмитрий",
        lastName: "Козлов",
        email: "kozlov.dmitry@school.edu",
        avatar: "/avatars/male3.png",
        gender: "male",
        averageGrade: 60,
        lastActive: "2025-05-08T12:20:00",
      },
      {
        id: "s105",
        firstName: "Анна",
        lastName: "Новикова",
        email: "novikova.anna@school.edu",
        avatar: "/avatars/female3.png",
        gender: "female",
        averageGrade: 88,
        lastActive: "2025-05-10T09:10:00",
      },
    ],
  },
  {
    id: 2,
    name: "Физика 10А",
    subject: "Физика",
    description: "Курс по физике с упором на эксперименты и практические задания.",
    schedule: "Вторник, четверг — 11:00–12:30",
    classroom: "Кабинет 310",
    entryCode: "PHYS10A",
    teacher: "Иванова Елена Петровна",
    activeAssignments: 2,
    image: "/class/physics.jpg",
    students: [
      {
        id: "s201",
        firstName: "Екатерина",
        lastName: "Воронова",
        email: "voronova.ekaterina@school.edu",
        avatar: "/avatars/female2.png",
        gender: "female",
        averageGrade: 91,
        lastActive: "2025-05-09T15:20:00",
      },
      {
        id: "s202",
        firstName: "Никита",
        lastName: "Фомин",
        email: "fomin.nikita@school.edu",
        avatar: "/avatars/male1.png",
        gender: "male",
        averageGrade: 67,
        lastActive: "2025-05-10T08:40:00",
      },
      {
        id: "s203",
        firstName: "Елена",
        lastName: "Крылова",
        email: "krylova.elena@school.edu",
        avatar: "/avatars/female3.png",
        gender: "female",
        averageGrade: 74,
        lastActive: "2025-05-07T12:00:00",
      },
      {
        id: "s204",
        firstName: "Максим",
        lastName: "Орлов",
        email: "orlov.maxim@school.edu",
        avatar: "/avatars/male3.png",
        gender: "male",
        averageGrade: 81,
        lastActive: "2025-05-10T11:30:00",
      },
      {
        id: "s205",
        firstName: "Дарья",
        lastName: "Зайцева",
        email: "zaitseva.darya@school.edu",
        avatar: "/avatars/female1.png",
        gender: "female",
        averageGrade: 88,
        lastActive: "2025-05-08T13:45:00",
      },
      {
        id: "s206",
        firstName: "Андрей",
        lastName: "Сорокин",
        email: "sorokin.andrey@school.edu",
        avatar: "/avatars/male2.png",
        gender: "male",
        averageGrade: 70,
        lastActive: "2025-05-06T17:15:00",
      },
    ],
  },
]
