"""
Pydantic schemas (DTOs - Data Transfer Objects)
"""

from app.schemas.classrooms import (
    ClassroomBase,
    ClassroomCreate,
    ClassroomDetailResponse,
    ClassroomResponse,
    ClassroomUpdate,
    InviteCreate,
    InviteResponse,
    JoinClassroomRequest,
)
from app.schemas.homework import (
    AnswerSubmit,
    HomeworkBase,
    HomeworkCreate,
    HomeworkDetailResponse,
    HomeworkResponse,
    HomeworkUpdate,
    ProblemBase,
    ProblemCreate,
    ProblemFullResponse,
    ProblemResponse,
    ProblemUpdate,
    StatisticsBase,
    StatisticsCreate,
    StatisticsResponse,
    StatisticsUpdate,
)
from app.schemas.lessons import (
    LessonBase,
    LessonCreate,
    LessonDetailResponse,
    LessonResponse,
    LessonUpdate,
    TheoryMaterialBase,
    TheoryMaterialCreate,
    TheoryMaterialResponse,
    TheoryMaterialUpdate,
)
from app.schemas.users import (
    LoginRequest,
    UserLogin,
    StudentBase,
    StudentCreate,
    StudentResponse,
    StudentUpdate,
    TeacherBase,
    TeacherCreate,
    TeacherResponse,
    TeacherUpdate,
    TokenResponse,
    UserBase,
    UserCreate,
    UserInDB,
    UserRole,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Users
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "TeacherBase",
    "TeacherCreate",
    "TeacherUpdate",
    "TeacherResponse",
    "StudentBase",
    "StudentCreate",
    "StudentUpdate",
    "StudentResponse",
    "LoginRequest",
    "UserLogin",
    "TokenResponse",
    "UserRole",
    # Classrooms
    "ClassroomBase",
    "ClassroomCreate",
    "ClassroomUpdate",
    "ClassroomResponse",
    "ClassroomDetailResponse",
    "InviteCreate",
    "InviteResponse",
    "JoinClassroomRequest",
    # Lessons
    "LessonBase",
    "LessonCreate",
    "LessonUpdate",
    "LessonResponse",
    "LessonDetailResponse",
    "TheoryMaterialBase",
    "TheoryMaterialCreate",
    "TheoryMaterialUpdate",
    "TheoryMaterialResponse",
    # Homework
    "HomeworkBase",
    "HomeworkCreate",
    "HomeworkUpdate",
    "HomeworkResponse",
    "HomeworkDetailResponse",
    "ProblemBase",
    "ProblemCreate",
    "ProblemUpdate",
    "ProblemResponse",
    "ProblemFullResponse",
    "StatisticsBase",
    "StatisticsCreate",
    "StatisticsUpdate",
    "StatisticsResponse",
    "AnswerSubmit",
]
