import { Notification } from "./types"

export const mockNotifications: Notification[] = [
  {
    id: 1,
    type: "homework_new",
    title: "Новое домашнее задание",
    description: "Алгебра: Решение квадратных уравнений",
    date: "2025-05-11T14:30:00",
    read: false,
    link: "/student/class/1/homework/5",
    linkText: "Перейти к заданию",
    classTitle: "Математика 10А",
  },
  {
    id: 2,
    type: "class_enrollment",
    title: "Вы были зачислены в класс",
    description: "Теперь вы участник класса 'Математика 10А'",
    date: "2025-05-11T12:15:00",
    read: false,
    link: "/student/class/1",
    linkText: "Открыть класс",
    classTitle: "Математика 10А",
  },
  {
    id: 3,
    type: "homework_graded",
    title: "Задание проверено",
    description: "Вы получили оценку 5 за контрольную по тригонометрии",
    date: "2025-05-10T16:45:00",
    read: true,
    link: "/student/class/2/homework/3",
    linkText: "Посмотреть результат",
    classTitle: "Математика 10А",
  },
  {
    id: 4,
    type: "deadline",
    title: "Скоро дедлайн",
    description: "Срок сдачи задания 'Анализ стихотворения' — завтра",
    date: "2025-05-10T09:30:00",
    read: false,
    link: "/student/class/3/homework/7",
    linkText: "Перейти к заданию",
    classTitle: "Литература 10А",
  },
  {
    id: 5,
    type: "class_expulsion",
    title: "Вы были удалены из класса",
    description: "Ваш доступ к классу 'Физика 10А' был отозван",
    date: "2025-05-08T09:00:00",
    read: false,
    link: "/profile",
    linkText: "Подробнее",
    classTitle: "Физика 10А",
  },
]
